// Code generated by weaver. DO NOT EDIT.
// Source: registry/attributes.yaml
// Run `make generate` to regenerate.

package semconv

// Attribute key constants generated from the OTel Weaver registry.
// All instrumentation MUST reference these constants — no magic strings.
const (

// AttrExporterTarget is the key for the exporter.target attribute.
	// The configured scrape target identifier (e.g., org/repo slug).
	// Stability: development
	AttrExporterTarget = "exporter.target"
// AttrGitHubIssueState is the key for the github.issue.state attribute.
	// Current state of the GitHub issue.
	// Stability: development
	AttrGitHubIssueState = "github.issue.state"
// AttrGitHubIssueLabel is the key for the github.issue.label attribute.
	// A label applied to the GitHub issue.
	// Stability: development
	AttrGitHubIssueLabel = "github.issue.label"
// AttrGitHubOrg is the key for the github.org attribute.
	// GitHub organization or user account name.
	// Stability: development
	AttrGitHubOrg = "github.org"
// AttrGitHubPrLabel is the key for the github.pr.label attribute.
	// A label applied to the pull request.
	// Stability: development
	AttrGitHubPrLabel = "github.pr.label"
// AttrGitHubPrReviewStatus is the key for the github.pr.review_status attribute.
	// Aggregate review status of the pull request.
	// Stability: development
	AttrGitHubPrReviewStatus = "github.pr.review_status"
// AttrGitHubPrState is the key for the github.pr.state attribute.
	// Current state of the pull request.
	// Stability: development
	AttrGitHubPrState = "github.pr.state"
// AttrGitHubRepo is the key for the github.repo attribute.
	// GitHub repository name (without org prefix).
	// Stability: development
	AttrGitHubRepo = "github.repo"
// AttrRenovateDashboardSection is the key for the renovate.dashboard.section attribute.
	// Section within the Renovate dependency dashboard issue.
	// Stability: development
	AttrRenovateDashboardSection = "renovate.dashboard.section"


)

// Enum values for typed attribute constants.
const (










// Values for github.issue.state
AttrGitHubIssueStateOpen = "open"
AttrGitHubIssueStateClosed = "closed"

// Values for github.pr.review_status
AttrGitHubPrReviewStatusApproved = "approved"
AttrGitHubPrReviewStatusChangesRequested = "changes_requested"
AttrGitHubPrReviewStatusPending = "pending"
AttrGitHubPrReviewStatusNone = "none"



// Values for github.pr.state
AttrGitHubPrStateOpen = "open"
AttrGitHubPrStateClosed = "closed"
AttrGitHubPrStateDraft = "draft"
AttrGitHubPrStateMerged = "merged"





// Values for renovate.dashboard.section
AttrRenovateDashboardSectionAwaitingSchedule = "awaiting-schedule"
AttrRenovateDashboardSectionRateLimited = "rate-limited"
AttrRenovateDashboardSectionPendingApproval = "pending-approval"
AttrRenovateDashboardSectionPending = "pending"




)