// Code generated by weaver. DO NOT EDIT.
// Source: registry/attributes.yaml
// Run `make generate` to regenerate.

package semconv

// Attribute key constants generated from the OTel Weaver registry.
// All instrumentation MUST reference these constants — no magic strings.
const (


	// AttrExporterTarget is the key for the exporter.target attribute.
	// The configured scrape target identifier (e.g., org/repo slug).
	// Stability: development
	AttrExporterTarget = "exporter.target"

	// AttrGithubIssueLabel is the key for the github.issue.label attribute.
	// A label applied to the GitHub issue.
	// Stability: development
	AttrGithubIssueLabel = "github.issue.label"

	// AttrGithubOrg is the key for the github.org attribute.
	// GitHub organization or user account name.
	// Stability: development
	AttrGithubOrg = "github.org"

	// AttrGithubPrLabel is the key for the github.pr.label attribute.
	// A label applied to the pull request.
	// Stability: development
	AttrGithubPrLabel = "github.pr.label"

	// AttrGithubPrReviewstatus is the key for the github.pr.review_status attribute.
	// Aggregate review status of the pull request.
	// Stability: development
	AttrGithubPrReviewstatus = "github.pr.review_status"

	// AttrGithubPrState is the key for the github.pr.state attribute.
	// Current state of the pull request.
	// Stability: development
	AttrGithubPrState = "github.pr.state"

	// AttrGithubRepo is the key for the github.repo attribute.
	// GitHub repository name (without org prefix).
	// Stability: development
	AttrGithubRepo = "github.repo"

	// AttrRenovateDashboardSection is the key for the renovate.dashboard.section attribute.
	// Section within the Renovate dependency dashboard issue.
	// Stability: development
	AttrRenovateDashboardSection = "renovate.dashboard.section"


)

// Enum values for typed attribute constants.
const (











	// Values for github.pr.review_status

	AttrGithubPrReviewstatusApproved = "approved"

	AttrGithubPrReviewstatusChangesrequested = "changes_requested"

	AttrGithubPrReviewstatusPending = "pending"

	AttrGithubPrReviewstatusNone = "none"




	// Values for github.pr.state

	AttrGithubPrStateOpen = "open"

	AttrGithubPrStateClosed = "closed"

	AttrGithubPrStateDraft = "draft"






	// Values for renovate.dashboard.section

	AttrRenovateDashboardSectionAwaitingschedule = "awaiting-schedule"

	AttrRenovateDashboardSectionRatelimited = "rate-limited"

	AttrRenovateDashboardSectionPendingapproval = "pending-approval"

	AttrRenovateDashboardSectionPending = "pending"




)